language: python
python:
    - "2.7"
addons:
    apt:
        packages:
          - python-scipy
          - gfortran
          - libatlas-dev
          - liblapack-dev
install:
    python setup.py install
script:
    python setup.py test
